#+TITLE: 42sh
#+AUTHOR: Christophe Dronne
#+DATE: Fri Feb 14 10:00:40 2025
#+LANGUAGE: en


** Description
This project is being worked on for my studies
at EPITECH. Since the actual project is split
into 3 repositories, I decided to create my own
in order to keep track of my progress and organize
the project better.

** Documentation
For documentation, please check out the [[https://github.com/Bard-Gaming/42sh/tree/main/docs][docs]].

** Compile Instructions
This project uses ~GNU Make~ to compile.

*** Release
The *release* version of mysh can be compiled
by simply running make:
#+begin_src bash
make
#+end_src
/Note: this is analogous to running/ ~make mysh~


*** Debug
The *debug* version of mysh can be compiled
by running make with the ~debug~ rule:
#+begin_src bash
make debug
#+end_src


*** Sanitized
The *sanitized* version of mysh can be compiled
by running make with the ~sanitize~ rule:
#+begin_src bash
make sanitize
#+end_src
/Note: this version should only be used for testing/


*** Cleanup
When you're done, you can use the ~clean~ rule
to delete any temporary files, and the ~fclean~
rule to delete all compiled files.
