#+TITLE: 42sh Builtin Commands
#+AUTHOR: Christophe DRONNE
#+DATE: Wed Feb 12 21:46:06 2025
#+LANGUAGE: en


* Navigation
This section covers builtin commands that allow you
to navigate your OS's files and directories.

** cd
The ~cd~ command allows you to change to a given
directory. If no argument is given, this defaults
to the current user's home directory, as specified
in the environment.

*** Arguments
- ~path~? : path to change directory to (relative or absolute)

*** Example
#+begin_src bash
cd  # changes directory to $HOME
cd ~  # ^ same as previous line
cd dir1/dir2  # changes to dir2 which is in dir1 relative to current work directory

cd nonexistant_dir  # error
cd dir1 dir1/dir2  # error (too many args)
#+end_src


* Environment
This section covers builtins that manipulate the shell's
environment.

** setenv
The ~setenv~ command allows you to add or overwrite values
that are stored in the environment. If no arguments are given,
the current environment is displayed instead (same as the [[*env][env]] command).

*** Arguments
- ~name~? : name of the value that should be added to the environment
- ~value~? : value to be associated with the name in the environment (default: ~""~)

*** Example
#+begin_src bash
setenv  # displays environment (same as calling env)

setenv a  # sets the env variable "a" to value ""
setenv a 3  # sets the env variable "a" to value "3"

setenv a b c  # error
#+end_src

** env
The ~env~ command allows you to display the current
environment. It does not take any arguments.

*** Example
#+begin_src bash
env  # displays the environment

env a  # error
#+end_src

** unsetenv
The ~unsetenv~ command allows you to remove one or more
values from the environment.

*** Arguments
- ~name~: name of the value to be removed
- ~names~\ast: names of the values to be removed

*** Example
#+begin_src bash
setenv a "hello"  # creates envvar
env  # displays a=hello
unsetenv a  # removes envvar
env  # doesn't display a

setenv a "test1"
setenv b "test2"
env
unsetenv a b  # removes both a and b

unsetenv  # error
#+end_src
